# Generated by Django 4.2.7 on 2024-04-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='images/')),
                ('product_description', models.CharField(max_length=1000)),
                ('product_category', models.CharField(max_length=30)),
                ('product_link', models.URLField(default='http://localhost:3000/product')),
                ('product_view_count', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
