# Generated by Django 4.2.7 on 2024-04-23 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_products_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_link',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_view_count',
        ),
    ]
